### ISSUE TITLE
M118 Error with RepRap

### ISSUE THREAD

**Issue by Wombat37** [bigtreetech/Bigtree3DPluginSuit#11]
Hi - thanks for the great feature!

I've found a minor error using your development on my BTT-E3-RRF v1.1 (RepRap v 3.2.2) motherboard with BTT-E3-TFT35 v3.0 (v3.27). I'm running RepRap firmware on the motherboard. When I create the BigTree modified g code file on Cura and save it on an SD card that I then insert into the TFT sd socket, all looks good - I see the icon of the print I'm about to make. It looks nice!

However when I select the file and try and print it (i.e. send it to the motherboard running RepRap), I get the following message on the TFT screen:

![STL_Preview](https://user-images.githubusercontent.com/42827647/117353738-8119dc00-ae7e-11eb-9a82-42d9fd8ea1b8.png)

Looking through the g code file I'm trying to print, I find the following:

![image](https://user-images.githubusercontent.com/42827647/117354072-ee2d7180-ae7e-11eb-939c-5c2e5b2409cb.png)

There's a big block of commented out data which I assume to be the graphic and then there's 3 lines containing M118 statements. These look to be in the wrong format for RepRap (expects something like M118 P0 S"Message").

It looks like this error message is only informational as the print goes ahead anyway. However, it does look messy and I assume easy to fix in your code.

I think there could be two approaches to a fix:

1. Create 2 versions of your code, the first for Marlin and the second for RepRap
2. Check the g code flavor configured in Cura (and shown in the line following the M118 statements) and apply the correct code accordingly.

Thanks again for your efforts.

**Comment by bigtreetech** [comment]
This is caused by the different usage of the two firmware for M118. You can refer to the following documentation link:
[https://marlinfw.org/docs/gcode/M118.html](url)
[https://reprap.org/wiki/G-code#M118:_Echo_message_on_host](url)

**Comment by Wombat37** [comment]
Good - I think we agree on the cause.

**Comment by radek8** [comment]
The M118 command is filament consumption information that is displayed on the TFT after printing (length, weight and price)
It also generates CURA and can be optionally switched on or off in the initial G code Cura

https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/blob/master/README.md


![image](https://user-images.githubusercontent.com/46979052/117578757-2daec480-b0f0-11eb-8b36-9e078d3fdc47.png)

**Comment by Wombat37** [comment]
I appreciate all this information - I had found the cause of the error, too.

I'm not sure why this plug-in needs to insert this M118 information in order to show a graphic icon of the model to be printed.

So how do I make the error disappear under RRF or will that not be supported?

**Comment by bigtreetech** [comment]
> I appreciate all this information - I had found the cause of the error, too.
> 
> I'm not sure why this plug-in needs to insert this M118 information in order to show a graphic icon of the model to be printed.
> 
> So how do I make the error disappear under RRF or will that not be supported?

Bigtree3DPluginSuit does not add M118, you can check your CURA configuration, the printer configuration of the CURA should have selected firmware type, did you select the firmware type of the Marlin?

**Comment by Wombat37** [comment]
OK - I think we're talking at cross purposes!

I'm now realizing that you think that this is a Cura problem not a problem with the PluginSuit. Apparently you believe that the plugin does not insert a M118 command into the  g code file but that I've applied some setting in Cura to make this happen.

OK, here's some further information that may help dissuade you of that belief...

Here are the last few lines from the Bigtree3DStore.py file in the GitHub repository (https://github.com/bigtreetech/Bigtree3DPluginSuit/blob/master/Bigtree3DPlugin/Bigtree3DStore.py): 

![image](https://user-images.githubusercontent.com/42827647/117753178-0b976e00-b1e6-11eb-90aa-95ae3ed8cc25.png)

Further, here's the beginning of the same Cura model g code output saved with and without the plug-in applied. No other changes have been made.

No Plugin:
![image](https://user-images.githubusercontent.com/42827647/117753793-17376480-b1e7-11eb-8448-c16f4fb9364b.png)

With Plugin
![image](https://user-images.githubusercontent.com/42827647/117753971-6aa9b280-b1e7-11eb-96be-54df2dba6556.png)

I understand that the Plugin is not expected or meant to insert M118 commands - but there is the hard evidence in both the code and in the resultant g code files.

Note that these g code files also indicate that RepRap flavor g code was selected in Cura.

Please let me know if my conclusions that this is a problem with the plugin are incorrect.

**Comment by Wombat37** [comment]
I suppose the irony is that now I've been looking through this code and understand much of it, I can make the fix myself on my system - but that wouldn't help anyone else.

**Comment by bigtreetech** [comment]
> I suppose the irony is that now I've been looking through this code and understand much of it, I can make the fix myself on my system - but that wouldn't help anyone else.

In the latest update, we fixed the firmware adaptation of the M118 instruction.

**Comment by radek8** [comment]
Look and #6

**Comment by bigtreetech** [comment]
> Look and #6

Yes, it is really caused by the combined content here, and the problem occurred because of the failure to consider the adaptation of different firmware before. You can try the current repair version, and no abnormality has been found in my test. If there is any problem, you can still feedback to me, and I will deal with it in time.

**Comment by Wombat37** [comment]
Thank you for taking this 'bug' seriously. On the grand scale of problems I suppose this was very minor - however, I felt it to be important to report it so that this product (which I really like) will continue to improve.

I've installed the new plugin  files in my Cura plugin folder and have made some prints. I'm happy to report that the M118 error has now gone and I feel that the issue can be closed (I think I have to do that).

Thanks again - I really appreciate your efforts.
