### ISSUE TITLE
I would like to have the option for selecting the TFT type for plugin,

### ISSUE THREAD

**Issue by Tygrys-1** [bigtreetech/Bigtree3DPluginSuit#2]
The reason is the changed output file size, which fouls the progress and ETA estimation on printer. Currently all 4 resolutions are included, and that for 160x140 is kinda big. I suggest a configuration file with options to put in, no need for Cura interface as you probably want to set this once according to TFT type(s) you use.

**Comment by bigtreetech** [comment]
We have also found this problem, and we will generate according to actual usage in the subsequent updates to avoid too many ICONS affecting the judgment of printing time.
