### ISSUE TITLE
FR: Add option to eject removable drive from machine after using this plugin to save file

### ISSUE THREAD

**Issue by poldim** [bigtreetech/Bigtree3DPluginSuit#5]
It would be great if I could export the removable drive without having to go to Finder and hit the eject button on the device. _It's a small step for man, and a tiny leap for mankind._ 

- This is how the existing option to save to removable media currently operates in Cura
- Looks like you can find code to how Cura is doing this [HERE](https://github.com/Ultimaker/Cura/search?q=save+to+removable+drive&unscoped_q=save+to+removable+drive)
- This is related to #1 but not the same thing.

Image for reference of how Cura today:
<img width="405" alt="CE3_Light Switch Spacer, Dining - Ultimaker Cura 2020-09-14 21-49-37" src="https://user-images.githubusercontent.com/16869713/93167255-19d3cf80-f6d5-11ea-82d6-000142444ec7.png">

**Comment by bigtreetech** [comment]
The latest version supports direct export to USB disk.If there are any questions during the use, we are willing to listen.
