### ISSUE TITLE
background color

### ISSUE THREAD

**Issue by Subia75** [bigtreetech/Bigtree3DPluginSuit#7]
I really liked the plugin,
but I ask if it is possible to change the background color of the previews because I use a lot of black material and it is difficult to recognize the piece.
As you can see from the attached screen, the piece in black (called PSU cover) cannot be distinguished.

I ask if it is possible without making the change in your plugin but just setting it in my plugin.
Unfortunately I am unable to edit the correct file myself, and ask if possible to know where I can change the background from black to another color.

![IMG_20210203_145239](https://user-images.githubusercontent.com/67789797/106758100-693d7c80-6631-11eb-9083-7dfb6d45f4aa.jpg)
thank you

**Comment by bigtreetech** [comment]
Hello, I've kept you waiting. Today we updated the function of the icon plug-in, adding the setting of the icon background color; I hope you found it useful.

**Comment by Subia75** [comment]
Thanks for the reply.
