### ISSUE TITLE
typo in Bigtree3DStore.py

### ISSUE THREAD

**Issue by dimquea** [bigtreetech/Bigtree3DPluginSuit#8]
https://github.com/bigtreetech/Bigtree3DPluginSuit/blob/76319420ccfc7368e3f15c082614025df7ab09d6/Bigtree3DPlugin/Bigtree3DStore.py#L261
startwith Instead of start**s**with

**Comment by bigtreetech** [comment]
Thanks for your feedback, we have fixed the problem.
